version: "3"
services:
  eureka-server:
    build: eureka-server
    ports:
      - 8761:8761
  currency-service:
    build: currency-service
    ports:
      - 8081:8081
    depends_on:
      - eureka-server
      - db
  weather-service:
    build: weather-service
    ports:
      - 8082:8082
    depends_on:
      - eureka-server
      - db
  predict-service:
    build: predict-service
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - currency-service
      - weather-service
  db:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432